type: api
group: V2TIMOfflinePushManager
name: setOfflinePushConfig
features: 设置离线推送配置信息
version: 1.1.1
ignore: false
deprecated:
params:
  - type: number
    required: true
    name: businessID
    description: businessID 为对应厂商的证书 ID
  - type: string
    required: true
    name: token
    description: 应合规要求，在用户同意隐私协议登录成功后，分别初始化注册各个厂商推送服务，并在注册结果回调处保存注册成功后的 token
  - type: boolean
    required: true
    name: isTPNSToken
    description: 传false即可  
returnExample: |-
    V2TimCallback

    {
        code : number
        desc : string
    }
returnValues:
    - type: number
      name: code
      description: 请求结果[错误码](https://cloud.tencent.com/document/product/269/1671)
    - type: string
      name: desc
      description: 请求结果描述
example: true
