type: api
group: V2TIMGroupManager
name: refuseGroupApplication 
features: 拒绝某一条加群申请
version: 1.1.1
ignore: false
deprecated:
params:
  - type: string
    required: true
    name: groupID
    description: 加入的群组id
  - type: string
    required: false
    name: reason
    description: 拒绝原因
  - type: string
    required: true
    name: fromUser
    description: 请求者id
  - type: string
    required: true
    name: toUser
    description: 判决者id
  - type: number
    required: false
    name: addTime
    description: 申请时间
  - type: '[GroupApplicationTypeEnum]()'
    required: false
    name: type
    description: 申请类型
returnExample: |-
    V2TimCallback

    {
        code : number
        desc : string
    }
returnValues:
    - type: number
      name: code
      description: 请求结果[错误码](https://cloud.tencent.com/document/product/269/1671)
    - type: string
      name: desc
      description: 请求结果描述符
example: true
