type: api
group: V2TIMGroupManager
name: setGroupApplicationRead 
features: 标记所有群组申请列表为已读
version: 1.1.1
ignore: false
deprecated:
params:
returnExample: |-
    V2TimCallback

    {
        code : number
        desc : string
    }
returnValues:
    - type: number
      name: code
      description: 请求结果[错误码](https://cloud.tencent.com/document/product/269/1671)
    - type: string
      name: desc
      description: 请求结果描述符
example: true
