type: class
group: Group
name: V2TimGroupApplication
features: 群申请信息
version: 1.1.1
ignore: false
deprecated: 
attributes:
  - name: groupID
    type: string
    description: 群组 ID
  - name: fromUser
    type: string
    description: 请求者 userID
  - name: fromUserNickName
    type: string
    description: 请求者昵称
  - name: fromUserFaceUrl
    type: string
    description: 请求者头像
  - name: toUser
    type: string
    description: 判决者id，有人请求加群:0，邀请其他人加群:被邀请人用户 ID
  - name: addTime
    type: number
    description: 申请时间
  - name: requestMsg
    type: string
    description: 申请或邀请附加信息
  - name: handledMsg
    type: string
    description: 审批信息：同意或拒绝信息
  - name: type
    type: typeƒ
    description: 请求类型
    extra:
      - 0:申请入群
      - 1:邀请入群
  - name: handleStatus
    type: number
    description: 处理标志
    extra:
      - 0:未处理
      - 1:被他人处理
      - 2:自己已处理
  - name: handleResult
    type: number
    description: 处理结果
    extra:
      - 0:拒绝申请
      - 1:同意申请