type: class
group: Group
name: V2TimGroupApplicationResult
features: 加群申请列表，包含当前用户有资格处理的所有群的群申请信息。
version: 1.1.1
ignore: false
deprecated: 
attributes:
  - name: unreadCount
    type: number
    description: 未读的申请数量
  - name: groupApplicationList
    type: '[V2TimGroupApplication]()[]'
    description: 加群申请的列表