type: api
group: V2TIMFriendshipManager
name: acceptFriendApplication
features: 同意好友申请
version: 1.1.1
ignore: false
deprecated:
params:
  - type: '[FriendResponseTypeEnum]()'
    required: true
    name: responseType
    description: 建立好友关系时选择单向/双向好友关系
  - type: '[FriendApplicationTypeEnum]()'
    required: true
    name: type
    description: 加好友类型
  - type: string
    required: true
    name: userID
    description: 同意好友的用户id
returnExample: |-
    V2TimValueCallback<V2TimFriendOperationResult>

    {
        code : number
        desc : string
        data : {
            resultCode : number//同意操作请求错误码
            resultInfo : string//同意操作请求结果描述
            userID : string//被同意的用户id
        }
    }
returnValues:
    - type: number
      name: code
      description: 请求结果[错误码](https://cloud.tencent.com/document/product/269/1671)
    - type: string
      name: desc
      description: 请求结果描述
    - type: '[V2TimFriendOperationResult]()'
      name: data
      description: 同意好友申请请求的返回信息
example: true
