type: api
group: V2TIMFriendshipManager
name: getFriendApplicationList
features: 获取好友申请列表
version: 1.1.1
ignore: false
deprecated:
params:
returnExample: |-
    V2TimValueCallback<V2TimFriendApplicationResult>

    {
        code : number
        desc : string
        data : {
            friendApplicationList : V2TimFriendApplication[]//好友申请列表
            unreadCount : number//未读申请数量
        }
    }
returnValues:
    - type: number
      name: code
      description: 请求结果[错误码](https://cloud.tencent.com/document/product/269/1671)
    - type: string
      name: desc
      description: 请求结果描述符
    - type: '[V2TimFriendApplicationResult]()'
      name: data
      description: 好友申请列表信息
example: true
