type: class
group: User
name: V2TimFriendApplicationResult
features: 好友申请列表
version: 1.1.1
ignore: false
deprecated: 
attributes:
  - name: unreadCount
    type: number
    description: 好友申请未读数量
  - name: friendApplicationList
    type: '[V2TimFriendApplication]()[]'
    description: 好友申请列表