type: callback
group: 
name: OnApplicationProcessed
features: 加群请求已经被群主或管理员处理了（只有申请人能够收到）
version: 1.1.1
ignore: false
deprecated:
returnExample: |-
  OnApplicationProcessed = void Function(
  string groupID,
  V2TimGroupMemberInfo opUser,
  Boolean isAgreeJoin,
  string opReason
  )
returnValues:
  - type: string
    name: groupID
    description: 群 ID
  - type: '[V2TimGroupMemberInfo]()'
    name: opUser
    description: 处理人
  - type: Boolean
    name: isAgreeJoin
    description: 是否同意加群
  - type: string 
    name: opReason
    description: 处理原因
example: true
