type: callback
group: 
name: OnFriendApplicationListDeleted
features: 好友请求数量减少的回调
version: 1.1.1
ignore: false
deprecated:
returnExample: |-
  OnFriendApplicationListDeleted = void Function(
  string[] userIDList
  )
returnValues:
  - type: string[]
    name: userIDList
    description: 减少的好友请求的请求用户id列表
example: true
