type: callback
group: 
name: OnFriendApplicationListAdded 
features: 好友请求数量增加的回调
version: 1.1.1
ignore: false
deprecated:
returnExample: |-
  OnFriendApplicationListAdded = void Function(
  V2TimFriendApplication[] applicationList
  )
returnValues:
  - type: '[V2TimFriendApplication]()[]'
    name: applicationList
    description: 新增的好友请求信息列表
example: true
