type: callback
group: 
name: OnReceiveJoinApplication
features: 有新的加群请求（只有群主或管理员会收到）
version: 1.1.1
ignore: false
deprecated:
returnExample: |-
  OnReceiveJoinApplication = void Function(
  string groupID,
  V2TimGroupMemberInfo member,
  string opReason
  )
returnValues:
  - type: string
    name: groupID
    description: 群 ID
  - type: '[V2TimGroupMemberInfo]()'
    name: member
    description: 申请人
  - type: string
    name: opReason
    description: 申请原因
example: true
